version: '3.8'

services:
  web:
    build: .
    command: gunicorn configurations.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=configurations.settings.dev
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: f1
      POSTGRES_USER: soft
      POSTGRES_PASSWORD: soft
    ports:
      - "5432:5432"

  celery:
    build: .
    command: celery -A configurations worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=configurations.settings.dev
    depends_on:
      - db
      - redis

  redis:
    image: redis:7.0-alpine
    ports:
      - "6369:6379"


volumes:
  postgres_data:
